### ISSUE TITLE
Translate LANGUAGE to LINGUAGEM in the reference pages

### ISSUE THREAD

**Issue by robsoncouto** [arduino/reference-pt#45]
Hello @smellai , could you kindly translate LANGUAGE to LINGUAGEM at the bottom of the pages?
Like you did with EXAMPLE to EXEMPLO. 
You can have a look at  [this page](https://cdn.arduino.cc/reference/pt/language/functions/characters/isalpha/) to see what I am talking about.
Many thanks!

**Comment by smellai** [comment]
Yes I'll look at it as soon as possible, thanks

**Comment by robsoncouto** [comment]
Hi @smellai . Do you have any update on this?
Thanks!
