### ISSUE TITLE
Translate subcategories names

### ISSUE THREAD

**Issue by smellai** [arduino/reference-pt#5]
languageCode: "es"
title: "Arduino Reference"

params:
description: "The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords."
category:

name: "functions"
intro: "For controlling the Arduino board and performing computations."
subCategories:

name: "Main"
name: "Digital I/O"
name: "Analog I/O"
name: "Zero, Due & MKR Family"
name: "Advanced I/O"
name: "Time"
name: "Math"
name: "Trigonometry"
name: "Characters"
name: "Random Numbers"
name: "Bits and Bytes"
name: "External Interrupts"
name: "Interrupts"
name: "Communication"
child:
name: "Serial"
name: "Stream"
name: "USB"
child:
name: "Keyboard"
name: "Mouse"
name: "variables"
intro: "Arduino data types and constants."
subCategories:

name: "Constants"
name: "Conversion"
name: "Data Types"
name: "Variable Scope & Qualifiers"
name: "Utilities"
name: "structure"
intro: "The elements of Arduino (C++) code."
subCategories:

name: "Control Structure"
name: "Further Syntax"
name: "Arithmetic Operators"
name: "Comparison Operators"
name: "Boolean Operators"
name: "Pointer Access Operators"
name: "Bitwise Operators"
name: "Compound Operators"

**Comment by robsoncouto** [comment]
Hello @smellai . Hi have translated subcategories names as you asked:

languageCode: "pt"
title: "Documentação de Referência do Arduino"

params:
description: "A Documentação de Referência da linguagem Arduino, organizada nas palavra-chave: Funções, Variáveis e Estruturas."
category:

name: "Funções"
intro: "Para controlar a placa Arduino e realizar computações."
subCategories:

name: "Main"
name: "Entradas e Saídas Digitais"
name: "Entradas e Saídas Analógicas"
name: "Família Zero, Due e MKR"
name: "Entradas e Saídas Digitais"
name: "Funções Temporizadoras"
name: "Funções Matemáticas"
name: "Trigonometria"
name: "Caracteres"
name: "Números Aleatórios"
name: "Bits e Bytes"
name: "Interrupções Externas"
name: "Interrupções"
name: "Comunicação"
child:
name: "Serial"
name: "Stream"
name: "USB"
child:
name: "Keyboard"
name: "Mouse"
name: "Variáveis"
intro: "Tipos de dados e constantes da linguagem Arduino."
subCategories:

name: "Constantes"
name: "Conversão"
name: "Tipos de dados"
name: "Escope de variáveis e Qualificadores"
name: "Utilitários"
name: "Estruturas"
intro: "Os elementos da linguagem Arduino (C++)."
subCategories:

name: "Estruturas de controle"
name: "Outros elementos da sintaxe"
name: "Operadores Aritméticos"
name: "Operadores de Comparação"
name: "Operadores Boleanos"
name: "Operadores para Ponteiros"
name: "Operadores Bitwise (Bit-a-Bit)"
name: "Operadores de Atribuição Composta"

I have some questions tough. Are parentheses in the names ok? e.g "(C++)"
How can I fix the modifications I made before with the new tags? Sorry, I am used to Github some, but haven't had the opportunity to work with pull requests or branches. But I will get the hang of it in no time.
I have not translated the tags like 'keyboard' or 'main', as they are the names of the files or part of the Arduino environment.

**Comment by robsoncouto** [comment]
I guess I have to close the pull requests, edit the files again with the new tags and then make a pull request again. Is that it?

**Comment by smellai** [comment]
you can edit the pull request

**Comment by smellai** [comment]
Is this correct: Advanced I/O -> Entradas e Saídas Digitais ?

**Comment by robsoncouto** [comment]
Yes. Entradas=Input and Saídas=Output. I realized there is an old reference in portuguese here 
https://playground.arduino.cc/Portugues/Referencia
In there, they used the translation inside parentheses

**Comment by robsoncouto** [comment]
"you can edit the pull request"
Ah, alright. Found it.

**Comment by smellai** [comment]
@robsoncouto ok, but Advanced = Digitais?

**Comment by robsoncouto** [comment]
Ah, go it!  No, it is not.
Sorry for that, my bad. It should be:

languageCode: "pt"
title: "Documentação de Referência do Arduino"

params:
description: "A Documentação de Referência da linguagem Arduino, organizada nas palavra-chave: Funções, Variáveis e Estruturas."
category:

name: "Funções"
intro: "Para controlar a placa Arduino e realizar computações."
subCategories:

name: "Main"
name: "Entradas e Saídas Digitais"
name: "Entradas e Saídas Analógicas"
name: "Família Zero, Due e MKR"
name: "Entradas e Saídas Avançadas"
name: "Funções Temporizadoras"
name: "Funções Matemáticas"
name: "Trigonometria"
name: "Caracteres"
name: "Números Aleatórios"
name: "Bits e Bytes"
name: "Interrupções Externas"
name: "Interrupções"
name: "Comunicação"
child:
name: "Serial"
name: "Stream"
name: "USB"
child:
name: "Keyboard"
name: "Mouse"
name: "Variáveis"
intro: "Tipos de dados e constantes da linguagem Arduino."
subCategories:

name: "Constantes"
name: "Conversão"
name: "Tipos de dados"
name: "Escope de variáveis e Qualificadores"
name: "Utilitários"
name: "Estruturas"
intro: "Os elementos da linguagem Arduino (C++)."
subCategories:

name: "Estruturas de controle"
name: "Outros elementos da sintaxe"
name: "Operadores Aritméticos"
name: "Operadores de Comparação"
name: "Operadores Boleanos"
name: "Operadores para Ponteiros"
name: "Operadores Bitwise (Bit-a-Bit)"
name: "Operadores de Atribuição Composta"

**Comment by smellai** [comment]
Thank you! Do you want to translate the other homepage texts too?
```
- id: pageTitle
  translation: Language Reference

- id: pageDescription
  translation: "Arduino programming language can be divided in three main parts: structure, values (variables and constants), and functions."

- id: language
  translation: Language

- id: functions
  translation: functions

- id: variables
  translation: variables

- id: structure
  translation: structure

- id: libraries
  translation: Libraries

- id: glossary
  translation: Glossary

- id: editButton
  translation: Edit This Page

- id: license
  translation: "The Arduino Reference text is licensed under a <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">Creative Commons Attribution-Share Alike 3.0 License</a>."

- id: githubLink
  translation: "Find anything that can be improved? <a href=\"https://github.com/arduino/reference-en\">Suggest corrections and new documentation via GitHub.</a>"
```

**Comment by robsoncouto** [comment]
No problem.
It this alright?

`- id: pageTitle
  translation: Documentação de Referência da Linguagem Arduino

- id: pageDescription
  translation: "A linguagem de programação do Arduino pode ser dividida em três partes principais: estruturas, valores (variáveis e constantes) e funções."

- id: language
  translation: Linguagem

- id: functions
  translation: funções

- id: variables
  translation: variáveis

- id: structure
  translation: estrutura

- id: libraries
  translation: Bibliotecas

- id: glossary
  translation: Glossário

- id: editButton
  translation: Editar essa Página

- id: license
  translation: "A documentação de referência da linguagem Arduino está licenciada sob uma licença <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">Creative Commons Attribution-Share Alike 3.0</a>."

- id: githubLink
  translation: "Encontrou alguma coisa que pode ser melhorada? <a href=\"https://github.com/arduino/reference-pt\">Sugira correções e nova documentação via GitHub.</a>"
`
I noticed some inconsistency in casing.  for example, functions was in lower case, but library and Glossary were in upper case. So I left it that way in the translation.

**Comment by smellai** [comment]
yes this is ok thanks so much!

**Comment by robsoncouto** [comment]
You're welcome :)
