### ISSUE TITLE
Upload content to match reference-en

### ISSUE THREAD

**Issue by robsoncouto** [arduino/reference-pt#79]
Hi @smellai . Can you give me write permission to this repository?
The way I thought for translating while keeping up with the English version is:
First update the folder I want to translate to catch up with the en repo. Using git to push a copy of the last English version of the folder.
Then translate each file (inside the folder) individually as I have been doing, I strongly rely on the preview tool of the github online interface  to compare the translation and have a final revision on each file.
 Thanks!

**Comment by smellai** [comment]
It would be better if you can clone the whole repos locally and add PRs with multiple files. You can see previews using this https://asciidoclive.com

**Comment by robsoncouto** [comment]
Hi @smellai. I guess not. You may have missed my point, think of the preview tool on github as a tool that lets me compare the old version of the file with the new version, not a way of forecasting the formatting of the file. This way I can easily revise the translation.

**Comment by smellai** [comment]
ok, but you can ask to push the en folder with a PR or I can push a specific folder for you if you want

**Comment by robsoncouto** [comment]
Yes! But this way I may have to wait a whole day or the weekend just to start translating and then wait again for it to be accepted. 
Then, I would prefer to continue to translate the way I have been doing.
Having so much work just to translate a file will probably end up turning me down. It seems too troublesome.

**Comment by smellai** [comment]
Let's suppose you want to translate Variables -> Utilities -> sizeof.
- Go to https://github.com/arduino/reference-pt/blob/master/Language/Variables/Utilities/sizeof.adoc
- Click the 'raw' button 
- Get the content from https://raw.githubusercontent.com/arduino/reference-pt/master/Language/Variables/Utilities/sizeof.adoc
- Paste in the edit area of reference-pt corresponding page
- Start translation

Do you think it would be ok? I'm sorry for that, you're totally right, if you think the flow above is too tricky I'll update the english files.

**Comment by robsoncouto** [comment]
Hi @smellai , not tricky, it is pretty straightforward actually. But a lot of extra steps than just

- Start translation

Not only, but I would have to push first to be able to use the preview tool as I have been using. 
Please have a look at this example:
![github](https://user-images.githubusercontent.com/18122592/32753587-361ddc76-c8ac-11e7-8bc5-2f66e38ef60c.png)

We can easily spot that the "Returns" section has not been translated. That is why I don't use just git.
This thread is getting longer than needed. If you can not give me write permission, I understand, but I am convinced it would be the best.
I guess I will choose the other way around and push a folder, wait for you to accept it, then translate. But it  is still awful, don't you think?
Thanks

**Comment by smellai** [comment]
Ehy @robsoncouto ,
I replaced with "en" updated content all the "VARIÁVEIS" and "ESTRUTURAS" sections except for already translated semicolon page.
Also I replaced:
- Família Zero, Due e MKR
- Números Aleatórios
- Interrupções Externas
- Interrupções
- Comunicação
- USB

We moved Functions -> Main in Structure -> Sketch

**Comment by robsoncouto** [comment]
Thanks a ton, @smellai. I Really appreciate it. 
I won't be translating pages in the next few days tough, because I am buried in college stuff at the moment. But I will try to fix the last broken links and suggest some fixes in the main page.
