### ISSUE TITLE
Fixes in main page

### ISSUE THREAD

**Issue by robsoncouto** [arduino/reference-pt#88]
Hello @smellai, can you make these changes in the main page?

- "Escope  de variáveis e Qualificadores" should be "Escopo  de Variáveis e Qualificadores"

Just a typo
- "Família Zero, Due e MKR" should be "Apenas Zero, Due e Família MKR" 

My bad. At the time I did not know that there was a MKR family of boards, so I thought these three boards were the family. I put the "Apenas" to clarify, it is equivalent to "only", as these functions are available only in these boards.
- "Trigonometria" would be better as "Funções Trigonométricas"

So it matches the math and time sections above.

Less relevant, but desirable:
- "Estruturas de controle" -> "Estruturas de Controle"
- "Tipos de dados" -> "Tipos de Dados"
- "Outros elementos da sintaxe" -> "Outros Elementos da Sintaxe"

Thanks

**Comment by smellai** [comment]
Done thanks!
