### ISSUE TITLE
Translate Titles

### ISSUE THREAD

**Issue by robsoncouto** [arduino/reference-pt#89]
Hi @smellai , is it possible to translate titles?
I still had not to, as I only translated function pages up to now, but I was writing contribution guidelines and noticed many pages need their titles to be translated.
If so, do their names need to be translated as well? I mean, the semicolon page had its title translated, but never worked.

Ex:
```
title: "+" (translate?if needed)
title_expanded: "addition" (translate?)
categories: [ "Structure" ]
subCategories: [ "Operadores Aritméticos" ]
```

**Comment by robsoncouto** [comment]
Ah, and if you don't mid. Could you tell what these "All checks have failed" messages with red crosses mean in the PRs?
I know they are somehow synced with the webpage, should I ignore them?
Thanks!

**Comment by smellai** [comment]
"the semicolon page had its title translated, but never worked." -> what do you mean?
![image](https://user-images.githubusercontent.com/1763268/33201795-4c64410e-d0fa-11e7-95f1-8ddb62c59add.png)

title and title_expanded are used in the index page.

About drone checks, yes, please ignore them, thanks!

**Comment by robsoncouto** [comment]
You asked me what I meant and closed the issue :)
I can't open the semicolon page. It seems not highlighted in your screenshot too.

**Comment by smellai** [comment]
you have to click exactly on `;` -> https://www.arduino.cc/reference/pt/language/structure/further-syntax/semicolon/
I'll open an issue in the theme repo to fix this, thanks

**Comment by robsoncouto** [comment]
Ahhh. So sorry.
Totally missed that as I thought all links were highlighted. My bad :/
Thank you
