### ISSUE TITLE
DigitalRead see also title

### ISSUE THREAD

**Issue by smellai** [arduino/reference-pt#9]
https://github.com/arduino/reference-pt/blob/master/Language/Functions/Digital%20IO/digitalRead.adoc#see-also

**Comment by robsoncouto** [comment]
@smellai , in the same file, at the end there is this: 
`#EXAMPLE# Tutorial`
Why is that only the example is highlighted(and in capitals)? 
I want to translate it, but
`Tutorial de #EXEMPLO# (Em Inglês)`
would be rather strange

**Comment by smellai** [comment]
You can translate EXAMPLE -> EXAMPLO

![image](https://user-images.githubusercontent.com/1763268/31954267-72fc442e-b8e5-11e7-9f79-df6a7ce5998f.png)

**Comment by smellai** [comment]
you can see your translations rendered here: https://reference.arduino.cc/reference/pt/, don't worry if you don't see all the updates it will take a while to propagate changes. Note that we added a sentence in the left sidebar if you want to translate that too, thanks so much for your work

**Comment by robsoncouto** [comment]
Ah, got it. I was reading it as 'example tutorial', but when rendered I see what you mean.
Yes, I noticed the translation is getting online already, thanks a lot.
No problem at all :)

**Comment by robsoncouto** [comment]
"Doubts on how to use Github? Learn everything you need to know in this tutorial"
can be translated as:
"Dúvidas sobre como usar o Github? Aprenda tudo o que precisa saber nesse tutorial"
